name: cerbos-rag-demo

services:
  chroma:
    image: chromadb/chroma
    ports:
      - 5666:5666
    command: "--workers 1 --host 0.0.0.0 --port 5666 --proxy-headers --log-config chromadb/log_config.yml --timeout-keep-alive 30"
    environment:
      - IS_PERSISTENT=TRUE
      - CHROMA_PORT=5666
      - PERSIST_DIRECTORY=/chroma/chroma
    healthcheck:
      test:
        ["CMD", "/bin/bash", "-c", "cat < /dev/null > /dev/tcp/localhost/8001"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./chroma/:/chroma/chroma

  cerbos:
    image: ghcr.io/cerbos/cerbos:0.40.0
    ports:
      - 3592:3592
      - 3593:3593
    volumes:
      - ./policies:/policies
    command: "server"
