name: cerbos-rag-demo-chroma

services:
  chroma:
    image: chromadb/chroma
    network_mode: host
    ports:
      - 5666:5666
    command: "--workers 1 --host 0.0.0.0 --port 5666 --proxy-headers --log-config chromadb/log_config.yml --timeout-keep-alive 30"
    environment:
      - IS_PERSISTENT=TRUE
      - CHROMA_PORT=5666
      - PERSIST_DIRECTORY=/chroma/chroma
    healthcheck:
      test:
        ["CMD", "/bin/bash", "-c", "cat < /dev/null > /dev/tcp/localhost/5666"]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - ./chroma/:/chroma/chroma

  cerbos:
    network_mode: host
    image: ghcr.io/cerbos/cerbos:0.40.0
    ports:
      - 3592:3592
      - 3593:3593
    volumes:
      - ./policies:/policies
    command: "server"

  app:
    network_mode: host
    build: "."
    environment:
      - DATABASE_URL=file:./dev.db
      - EMBEDDING_MODEL=mxbai-embed-large
      - LLM=llama3.1
      - VECTOR_STORE=chroma
      - CHROMA_PORT=5666
      - CHROMA_ENDPOINT=http://localhost:5666
    depends_on:
      chroma:
        condition: service_healthy
      cerbos:
        condition: service_started
